# Settings for the Telegram side
telegram:
  # Bot username in Telegram
  botUsername: MinecraftTGBridgeBot
  # Telegram bot token as given by BotFather
  botToken: 1234
  # Telegram chat ID
  chatID: 1234
  # Telegram thread ID.
  # The bot will post messages from this thread in Minecraft chat,
  # and it will post messages from Minecraft chat in this thread.
  # If your chat does not have threads, set this to `null`.
  threadID: 1234
  # Template of messages to be posted in Telegram chat.
  # MarkdownV2 is supported in the template,
  # but escaped in the substituted strings (e.g., messages and names).
  #
  # Supported substitutions:
  # {username} - player name
  # {message} - message
  #
  # To escape curly braces, use backslash, e.g. '\{foo}' will be posted as '{foo}'.
  # To escape backslash, use another backslash.
  messageTemplate: "*{username}*:\n{message}"
  # Whether to allow the /chatid command that shows current chat and thread IDs
  allowChatIDCommand: false
  # Whether to announce getting Minecraft advancements
  announceAdvancements: true
  # Template of advancement announcements to be posted in Telegram chat.
  # MarkdownV2 is supported in the template,
  # but escaped in the substituted strings (e.g., messages and names).
  #
  # Supported substitutions:
  # {username} - player name
  # {title} - advancement title
  # {description} - advancement description
  #
  # To escape curly braces, use backslash, e.g. '\{foo}' will be posted as '{foo}'.
  # To escape backslash, use another backslash.
  advancementTemplate: "*{username}* has made an advancement: {title}\n\n_{description}_"
  # Whether to announce players joining the game
  announcePlayersJoining: true
  # Template of player joining announcements to be posted in Telegram chat.
  # MarkdownV2 is supported in the template,
  # but escaped in the substituted strings (e.g., messages and names).
  #
  # Supported substitutions:
  # {username} - player name
  #
  # To escape curly braces, use backslash, e.g. '\{foo}' will be posted as '{foo}'.
  # To escape backslash, use another backslash.
  playerJoinTemplate: "*{username}* has joined the game"
  # Whether to announce players quitting the game
  announcePlayersQuitting: true
  # Template of player quitting announcements to be posted in Telegram chat.
  # MarkdownV2 is supported in the template,
  # but escaped in the substituted strings (e.g., messages and names).
  #
  # Supported substitutions:
  # {username} - player name
  #
  # To escape curly braces, use backslash, e.g. '\{foo}' will be posted as '{foo}'.
  # To escape backslash, use another backslash.
  playerQuitTemplate: "*{username}* has left the game"
  # Whether to announce player deaths
  announcePlayerDeaths: true
  # Template of player death announcements to be posted in Telegram chat.
  # MarkdownV2 is supported in the template,
  # but escaped in the substituted strings (e.g., messages and names).
  #
  # Supported substitutions:
  # {username} - player name
  # {message} - the Minecraft death message
  #
  # To escape curly braces, use backslash, e.g. '\{foo}' will be posted as '{foo}'.
  # To escape backslash, use another backslash.
  playerDeathTemplate: "*{username}* has perished\n\n_{message}_"
  # Whether to forward the /me command
  forwardMeCommand: true
  # Template of player /me commands to be posted in Telegram chat.
  # MarkdownV2 is supported in the template,
  # but escaped in the substituted strings (e.g., messages and names).
  #
  # Supported substitutions:
  # {username} - player name
  # {message} - the Minecraft death message
  #
  # To escape curly braces, use backslash, e.g. '\{foo}' will be posted as '{foo}'.
  # To escape backslash, use another backslash.
  playerMeCommandTemplate: "_*{username}* {message}_"

# Settings for the Minecraft side
mc:
  # Template of messages to be posted in Minecraft chat.
  # Formatting codes are supported in the template,
  # but removed from substituted strings (e.g., messages and names).
  #
  # Supported substitutions:
  # {firstName} - user's first name
  # {lastName} - user's last name, if it exists. Otherwise, {firstName} will be used.
  # {fullName} - user's first and last name separated with space
  # {username} - username, if it exists. Otherwise, {fullName} will be used.
  # {message} - message
  #
  # To escape curly braces, use backslash, e.g. '\{foo}' will be posted as '{foo}'.
  # To escape backslash, use another backslash.
  messageTemplate: "§b[TG]§r <{fullName}> {message}"
  # Whether to format messages in Minecraft similarly to original formatting in Telegram.
  # Currently, that preserves bold, italic, underline, strikethrough and spoilers.
  passFormattingFromTelegram: true
